Add Alerts Backend Folder To AeroApps
flightaware/aeroapps pull request #3
Opened 2022-06-16 19:11 UTC by OptimusIacobus

Add a folder to add functionality in the backend to give an endpoint
for creating alerts using AeroAPI. Also add Docker compose file to run
the alerts backend application.

[JIRA-7000](https://flightaware.atlassian.net/browse/BCK-7000)

2022-06-23 18:33 UTC, Dogrock requested changes

2022-06-24 18:06 UTC, OptimusIacobus commented on alerts_backend/python/app.py
> +            conn.execute(stmt, data_to_insert)
Resolved in #4

2022-06-24 18:07 UTC, OptimusIacobus commented on alerts_backend/python/app.py
> +             aircraft_type char(255), start char(255), end char(255))""")
Resolved in #4

2022-06-24 18:10 UTC, OptimusIacobus commented on alerts_backend/python/app.py
> +             aircraft_type char(255), start char(255), end char(255))""")
Revoled in #4

2022-06-27 20:56 UTC, Dogrock requested changes

2022-06-30 19:16 UTC, Dogrock commented on alerts_backend/python/app.py
> +app.run(host="0.0.0.0", port=5001, debug=True)
I think an accidental port change got through
```suggestion
app.run(host="0.0.0.0", port=5000, debug=True)
```

2022-07-01 14:45 UTC, merged