SQLite Capability to Store Alert Requests
flightaware/aeroapps pull request #4
Opened 2022-06-21 20:20 UTC by OptimusIacobus

Add code to the app to implement SQLAlchemy in creating a table if it
does not exist, and then inserting in to a table that tracks the
alerts created by the user. Modifies the docker file and docker compose
file so that a new volume is created for the app to store the SQLite
database.

JIRA-7001

2022-07-01 14:49 UTC, Dogrock approved these changes

2022-07-01 15:27 UTC, NasaGeek requested changes
Enjoy your dogpile review! Sorry for coming in late with these.

2022-07-01 15:27 UTC, NasaGeek commented on alerts_backend/python/app.py
> +table_name = "aeroapi_alerts_table"
I'd avoid including the `_table` suffix.

2022-07-01 15:27 UTC, NasaGeek commented on alerts_backend/python/app.py
> +@app.before_first_request
Wow this is really cool, didn't know it existed. I'd recommend just doing this on server launch, though (like at the module level). Wouldn't want to wait until just before the first request to find out there's something wrong with the db.

2022-07-01 15:27 UTC, NasaGeek commented on alerts_backend/python/app.py
> +        app.logger.info("Table successfully created / updated")
Are any updates to the table actually occurring?

2022-07-01 15:27 UTC, NasaGeek commented on alerts_backend/python/app.py
> +        app.logger.error(f"SQL error occurred during creation of table (CRITICAL - INSERT WILL FAIL): {e}")
This seems problematic enough that it's worth raising an exception instead of relying on the caller to check an error code

2022-07-01 15:27 UTC, NasaGeek commented on alerts_backend/python/app.py
> +        table_to_insert = Table(table_name, metadata, autoload_with=engine)
By defining your `Table` at a broader scope, you'll no longer need to re-reflect it on every insertion.

2022-07-01 15:42 UTC, OptimusIacobus commented on alerts_backend/python/app.py
> +    holder: Dict[str, Any] = data
Addressed in previous commit - no more using holder variable

2022-07-01 15:58 UTC, NasaGeek commented on alerts_backend/python/app.py
> +    holder: Dict[str, Any] = data
ah shoot, that's what I get for submitting stale PR comments

2022-07-06 20:01 UTC, NasaGeek commented on alerts_backend/python/app.py
> +table_name = "aeroapi_alert_configurations"
No reason not to just slip this into the table definition directly.

2022-07-07 15:22 UTC, NasaGeek commented on alerts_backend/python/app.py
> +from datetime import *
Best to avoid `*` imports so we always know where the symbols we use are coming from
```suggestion
from datetime import datetime
```

2022-07-07 15:22 UTC, NasaGeek commented on alerts_backend/python/app.py
> +            # Rename dates to avoid sql keyword "end" issue, and also change to Python datetime.date()
```suggestion
            # Rename dates to avoid sql keyword "end" issue, and also change to Python datetime.datetime()
```

2022-07-07 16:04 UTC, merged